name: Feature Request
description: Request a new feature or enhancement
title: "[Feature Request] "
labels: [feature request]
body:
  - type: markdown
    attributes:
      value: |
        Thank you providing helpful feedback on BoxBilling. Pleas fill out everything below to help provide a good feature request
  - type: textarea
    id: what-happened
    attributes:
      label: What is the idea?
      description: Please describe your feature request or enhancement in detail
      placeholder: I suggest..
      value: "Feature request"
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: Why would this be beneficial
      description: Please describe why this enhancement or new feature would benefit BoxBilling and it's users.
      placeholder: This would be helpful because..
      value: "Benefits"
