name: Task
description: Development task that is required. This report type is mostly for developers
title: "[Task] "
labels: [task]
body:
  - type: markdown
    attributes:
      value: |
        Development task that is required. This report type is mostly for developers
  - type: textarea
    id: what-happened
    attributes:
      label: What is the task
      description: Please describe the task and what it requires. A checklist is a good way to keep track of progress.
      placeholder: Enter task here
      value: "Enter task here"
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: Additional Notes
      description: Please provide any additional notes.
      placeholder: Additional notes
      value: "Additional notes"
